POST http://localhost:5000/createpost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDg5MjJlYTFlMGQyMDBlYjBjNmI4ZTEiLCJpYXQiOjE2MTk2MDQ1MjR9.2iZYERhGkeAZZb_8K6QNeiOF8TmiY-ilV1mtSGvz35c
Content-Type: application/json

{
    "title":"Great",
    "body":"Great body"
}